version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package -DskipTests
artifacts:
  files:
    - target/datacompare-0.0.1.jar